```{r changentcat, cache=cacheon}

changefunc <- function(data, changevar, popname) {
  cat_all <- data %>%
    filter(!is.na(!!sym(changevar))) %>%
    count(!!sym(changevar), .drop = F) %>%
    mutate(
      per = fn(n / sum(n) * 100, 1),
      ds = paste0(n, " (", per, "%)"),
      whfe = "Overall"
    ) %>%
    select(whfe, ds, !!sym(changevar))

  cat_whfe <- data %>%
    filter(!is.na(!!sym(changevar))) %>%
    group_by(whfe, .drop = F) %>%
    count(!!sym(changevar), .drop = F) %>%
    mutate(
      per = fn(n / sum(n) * 100, 1),
      ds = paste0(n, " (", per, "%)")
    ) %>%
    ungroup() %>%
    select(whfe, ds, !!sym(changevar))

  both <- bind_rows(cat_all, cat_whfe)

  both <- both %>%
    pivot_wider(names_from = c(whfe, !!sym(changevar)), values_from = ds) %>%
    mutate(pop = popname) %>%
    select(pop, everything())
}

changefunc2 <- function(data2, changevar2, tabname, tabnamexlsx) {
  change <- changefunc(data = data2, changevar = changevar2, popname = "Overall")
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_sex == "Female"), changevar = changevar2, popname = "Female"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_sex == "Male"), changevar = changevar2, popname = "Male"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_age_cat == "<75"), changevar = changevar2, popname = "<75y"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_age_cat == ">=75"), changevar = changevar2, popname = ">=75y"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_location == "In-patient"), changevar = changevar2, popname = "In-patient"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_location == "Out-patient"), changevar = changevar2, popname = "Out-patient"))
  change <- rbind(change, changefunc(data = data2 %>% filter(scream_gfrckdepi_cat == "<=30"), changevar = changevar2, popname = "eGFR <=30"))
  change <- rbind(change, changefunc(data = data2 %>% filter(scream_gfrckdepi_cat == ">30-<60"), changevar = changevar2, popname = "eGFR >30-<60"))
  change <- rbind(change, changefunc(data = data2 %>% filter(scream_gfrckdepi_cat == ">=60"), changevar = changevar2, popname = "eGFR >=60"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_sos_com_af == "No"), changevar = changevar2, popname = "No AF"))
  change <- rbind(change, changefunc(data = data2 %>% filter(shf_sos_com_af == "Yes"), changevar = changevar2, popname = "AF"))

  write.xlsx(change, paste0("./output/tabs/tabchange_", tabnamexlsx, "_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

  levs <- levels(rsdata %>% pull(!!sym(changevar2)))
  colnames(change) <- c("Population", rep(levs, 3))

  default_kable(change,
    caption = tabname,
    escape = TRUE
  ) %>%
    add_header_above(c(" " = 1, "Overall" = length(levs), "WHFE" = length(levs), "NWHFE" = length(levs)))
}

changefunc2(
  data2 = rsdata, changevar2 = "scream_ntprobnpstableprior",
  tabname = "Change in NT-proBNP from 6 (+/- 3 mo) prior to index (+/- 2 weeks) - Overall 4 change groups",
  tabnamexlsx = "priortoindex_4groups_overall"
)

changefunc2(
  data2 = rsdata %>% filter(shf_ef_cat == "HFrEF"), changevar2 = "scream_ntprobnpstableprior",
  tabname = "Change in NT-proBNP from 6 (+/- 3 mo) prior to index (+/- 2 weeks) - HFrEF 4 change groups",
  tabnamexlsx = "priortoindex_4groups_ref"
)

changefunc2(
  data2 = rsdata, changevar2 = "scream_ntprobnpstablepost",
  tabname = "Change in NT-proBNP from index (+/- 2 weeks) to 6 (+/- 3 mo) - Overall 4 change groups",
  tabnamexlsx = "indextopost_4groups_overall"
)

changefunc2(
  data2 = rsdata %>% filter(shf_ef_cat == "HFrEF"), changevar2 = "scream_ntprobnpstablepost",
  tabname = "Change in NT-proBNP from index (+/- 2 weeks) to 6 (+/- 3 mo) - HFrEF 4 change groups",
  tabnamexlsx = "indextopost_4groups_ref"
)

changefunc2(
  data2 = rsdata, changevar2 = "scream_ntprobnpstableprior2",
  tabname = "Change in NT-proBNP from 6 (+/- 3 mo) prior to index (+/- 2 weeks) - Overall 3 change groups",
  tabnamexlsx = "priortoindex_3groups_overall"
)

changefunc2(
  data2 = rsdata %>% filter(shf_ef_cat == "HFrEF"), changevar2 = "scream_ntprobnpstableprior2",
  tabname = "Change in NT-proBNP from 6 (+/- 3 mo) prior to index (+/- 2 weeks) - HFrEF 3 change groups",
  tabnamexlsx = "priortoindex_3groups_ref"
)

changefunc2(
  data2 = rsdata, changevar2 = "scream_ntprobnpstablepost2",
  tabname = "Change in NT-proBNP from index (+/- 2 weeks) to 6 (+/- 3 mo) - Overall 3 change groups",
  tabnamexlsx = "indextopost_3groups_overall"
)

changefunc2(
  data2 = rsdata %>% filter(shf_ef_cat == "HFrEF"), changevar2 = "scream_ntprobnpstablepost2",
  tabname = "Change in NT-proBNP from index (+/- 2 weeks) to 6 (+/- 3 mo) - HFrEF 3 change groups",
  tabnamexlsx = "indextopost_3groups_ref"
)
```

 
```{r changentkont, cache=cacheon}
changefunckont <- function(data, tabname) {
  kont_all <- data %>%
    mutate(ntdiff = scream_ntprobnp3mopost - scream_ntprobnp3moprior) %>%
    filter(!is.na(ntdiff)) %>%
    summarise(
      n = n(),
      med = fn(median(ntdiff), dig = 1),
      q1 = fn(quantile(ntdiff, probs = 0.25), dig = 1),
      q3 = fn(quantile(ntdiff, probs = 0.75), dig = 1),
      min = fn(min(ntdiff), dig = 0),
      max = fn(max(ntdiff), dig = 0)
    ) %>%
    mutate(
      ds = paste0(n, ", ", med, " (", min, ", ", q1, ", ", q3, ", ", max, ")"),
      "NT-proBNP" = "N, Median (min, q1, q3, max)",
      whfe = "Overall"
    ) %>%
    select(whfe, "NT-proBNP", ds)

  kont_whfe <- data %>%
    mutate(ntdiff = scream_ntprobnp3mopost - scream_ntprobnp3moprior) %>%
    filter(!is.na(ntdiff)) %>%
    group_by(whfe) %>%
    summarise(
      n = n(),
      med = fn(median(ntdiff), dig = 1),
      q1 = fn(quantile(ntdiff, probs = 0.25), dig = 1),
      q3 = fn(quantile(ntdiff, probs = 0.75), dig = 1),
      min = fn(min(ntdiff), dig = 0),
      max = fn(max(ntdiff), dig = 0)
    ) %>%
    mutate(ds = paste0(n, ", ", med, " (", min, ", ", q1, ", ", q3, ", ", max, ")")) %>%
    ungroup() %>%
    mutate("NT-proBNP" = "N, Median (min, q1, q3, max)") %>%
    select(whfe, "NT-proBNP", ds)

  both <- bind_rows(kont_all, kont_whfe)

  both <- both %>%
    pivot_wider(names_from = whfe, values_from = ds)

  default_kable(both,
    caption = paste0("Change in NT-proBNP from prior (3 months to 3 days prior to index) to post (1 day to 3 months post index) - ", tabname),
    escape = TRUE
  )
}

changefunckont(data <- rsdata, tabname = "Overall")
changefunckont(rsdata %>% filter(shf_ef_cat == "HFrEF"), "HFrEF")
```
