```{r freq306090nt, cache=cacheon}

tmplab <- left_join(
  rsdata %>% select(LopNr, shf_indexdtm),
  labnt,
  by = "LopNr"
) %>%
  mutate(
    tmptiment = as.numeric(labdtm - shf_indexdtm),
    nt = 1
  ) %>%
  filter(tmptiment >= -90 & tmptiment <= 90)

trendfunc <- function(timestart, timestop, timename, data) {
  tmplab2 <- tmplab %>%
    filter(tmptiment >= timestart & tmptiment <= timestop) %>%
    group_by(LopNr) %>%
    slice(1) %>%
    ungroup() %>%
    select(LopNr, nt)

  tmplab2 <- left_join(data,
    tmplab2,
    by = "LopNr"
  ) %>%
    filter(
      sos_outtime_death >= timestop
    ) %>%
    mutate(nt = replace_na(nt, 0))

  tmplab2_all <- tmplab2 %>%
    count(nt) %>%
    mutate(
      per = n / sum(n) * 100,
      ntot = paste0(n, "/", sum(n), " (", fn(per, 1), "%)"),
      "Time point" = timename,
      whfe = "Overall"
    ) %>%
    filter(nt == 1)

  tmplab2_whfe <- tmplab2 %>%
    group_by(whfe) %>%
    count(nt) %>%
    mutate(
      per = n / sum(n) * 100,
      ntot = paste0(n, "/", sum(n), " (", fn(per, 1), "%)"),
      "Time point" = timename
    ) %>%
    ungroup() %>%
    filter(nt == 1)

  out <- bind_rows(tmplab2_all, tmplab2_whfe)
}

trendfunc2 <- function(data2, popname) {
  trend <- trendfunc(timestart = -90, timestop = 0, timename = "90-0 days prior to index", data = data2)
  trend <- rbind(trend, trendfunc(-60, 0, "60-0 days prior to index", data2))
  trend <- rbind(trend, trendfunc(-30, 0, "30-0 days prior to index", data2))
  trend <- rbind(trend, trendfunc(-14, 0, "14-0 days prior to index", data2))
  trend <- rbind(trend, trendfunc(1, 14, "1-14 days post index", data2))
  trend <- rbind(trend, trendfunc(1, 30, "1-30 days post index", data2))
  trend <- rbind(trend, trendfunc(1, 60, "1-60 days post index", data2))
  trend <- rbind(trend, trendfunc(1, 90, "1-90 days post index", data2))

  trend <- trend %>%
    select(whfe, `Time point`, ntot) %>%
    pivot_wider(names_from = whfe, values_from = ntot)

  write.xlsx(trend,
    paste0(
      "./output/tabs/NT-proBNP testing within 14, 30, 60 and 90 days before and after the index date - ",
      popname, "_", Sys.Date(), ".xlsx"
    ),
    rowNames = FALSE, overwrite = TRUE
  )

  default_kable(trend,
    scale_down = F,
    caption = paste0("NT-proBNP testing within 14, 30, 60 and 90 days before and after the index date - ", popname),
    escape = TRUE
  )
}

trendfunc2(data2 = rsdata, "Overall")

trendfunc2(rsdata %>% filter(shf_ef_cat == "HFrEF"), "HFrEF")
```

```{r freq306090ntplot, cache = cacheon, dependson="freq306090nt", fig.cap = "NT-proBNP testing within 14, 30, 60 and 90 days before and after the index date", fig.show='hold', out.width="33%", fig.ncol=3, fig.subcap=c('Overall population Overall', 'Overall population WHFE', 'Overall population NWHFE', 'HFrEF Overall', 'HFrEF WHFE', 'HFrEF NWHFE')}

trendplot <- function(dataplot) {
  dataplot <- dataplot %>%
    mutate(row = 1:n()) %>%
    arrange(desc(row))

  dataplot$`Time point` <- forcats::fct_reorder(dataplot$`Time point`, dataplot$row)

  cexmy <- 1.1
  par(mar = c(4, 11, .5, 1) + 0.1)
  b <- barplot(dataplot %>% pull(per) ~ dataplot %>% pull(`Time point`),
    col = c(rep(global_colsblue[2], 4), rep(global_colsblue[6], 4)),
    horiz = TRUE, xlab = "Percent", ylab = "", cex.lab = cexmy,
    border = "white", axes = F, xlim = c(0, 100), names.arg = NA
  )

  axis(1, seq(0, 100, 20), cex.axis = cexmy)
  axis(2, at = b, labels = dataplot$`Time point`, line = 0, tick = FALSE, cex.axis = cexmy, las = 2, gap.axis = -10000000)
}

trend1 <- trendfunc(timestart = -90, timestop = 0, timename = "90-0 days prior to index", data = rsdata)
trend1 <- rbind(trend1, trendfunc(-60, 0, "60-0 days prior to index", rsdata))
trend1 <- rbind(trend1, trendfunc(-30, 0, "30-0 days prior to index", rsdata))
trend1 <- rbind(trend1, trendfunc(-14, 0, "14-0 days prior to index", rsdata))
trend1 <- rbind(trend1, trendfunc(1, 14, "1-14 days post index", rsdata))
trend1 <- rbind(trend1, trendfunc(1, 30, "1-30 days post index", rsdata))
trend1 <- rbind(trend1, trendfunc(1, 60, "1-60 days post index", rsdata))
trend1 <- rbind(trend1, trendfunc(1, 90, "1-90 days post index", rsdata))

trend2 <- trendfunc(timestart = -90, timestop = 0, timename = "90-0 days prior to index", data = rsdata %>% filter(shf_ef_cat == "HFrEF"))
trend2 <- rbind(trend2, trendfunc(-60, 0, "60-0 days prior to index", rsdata %>% filter(shf_ef_cat == "HFrEF")))
trend2 <- rbind(trend2, trendfunc(-30, 0, "30-0 days prior to index", rsdata %>% filter(shf_ef_cat == "HFrEF")))
trend2 <- rbind(trend2, trendfunc(-14, 0, "14-0 days prior to index", rsdata %>% filter(shf_ef_cat == "HFrEF")))
trend2 <- rbind(trend2, trendfunc(1, 14, "0-14 days post index", rsdata %>% filter(shf_ef_cat == "HFrEF")))
trend2 <- rbind(trend2, trendfunc(1, 30, "0-30 days post index", rsdata %>% filter(shf_ef_cat == "HFrEF")))
trend2 <- rbind(trend2, trendfunc(1, 60, "0-60 days post index", rsdata %>% filter(shf_ef_cat == "HFrEF")))
trend2 <- rbind(trend2, trendfunc(1, 90, "0-90 days post index", rsdata %>% filter(shf_ef_cat == "HFrEF")))

trendplot(dataplot = trend1 %>% filter(whfe == "Overall"))
trendplot(trend1 %>% filter(whfe == "WHFE"))
trendplot(trend1 %>% filter(whfe == "NWHFE"))

trendplot(dataplot = trend2 %>% filter(whfe == "Overall"))
trendplot(trend2 %>% filter(whfe == "WHFE"))
trendplot(trend2 %>% filter(whfe == "NWHFE"))
```             
