```{r tab1func, cache=cacheon}


tab1func <- function(data = rsdata, tabname) {

  # all 4 strata inc missing
  tabds <- print(CreateTableOne(
    vars = tabvars,
    data = data,
    strata = c("scream_nttest", "whfe")
  ),
  missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1, test = FALSE,
  noSpaces = TRUE,
  explain = FALSE
  )
  tabds <- as_tibble(cbind(var = rownames(tabds), tabds))

  # p within whfe
  tabp_whfe <- print(CreateTableOne(
    vars = tabvars,
    data = data %>% filter(whfe == "WHFE"),
    strata = "scream_nttest"
  ),
  missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1, test = TRUE,
  noSpaces = TRUE,
  explain = FALSE
  )
  tabp_whfe <- as_tibble(cbind(var = rownames(tabp_whfe), tabp_whfe)) %>%
    select(p) %>%
    rename(p_whfe = p)

  # p within nwhfe
  tabp_nwhfe <- print(CreateTableOne(
    vars = tabvars,
    data = data %>% filter(whfe == "NWHFE"),
    strata = "scream_nttest"
  ),
  missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1, test = TRUE,
  noSpaces = TRUE,
  explain = FALSE
  )
  tabp_nwhfe <- as_tibble(cbind(var = rownames(tabp_nwhfe), tabp_nwhfe)) %>%
    select(p) %>%
    rename(p_nwhfe = p)

  # p within tested
  tabp_tested <- print(CreateTableOne(
    vars = tabvars,
    data = data %>% filter(scream_nttest == "Yes"),
    strata = "whfe"
  ),
  missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1, test = TRUE,
  noSpaces = TRUE,
  explain = FALSE
  )
  tabp_tested <- as_tibble(cbind(var = rownames(tabp_tested), tabp_tested)) %>%
    select(p) %>%
    rename(p_tested = p)

  tab1 <- bind_cols(tabds, tabp_whfe, tabp_nwhfe, tabp_tested) %>%
    select(var, Missing, "Yes:WHFE", "No:WHFE", p_whfe, "Yes:NWHFE", "No:NWHFE", p_nwhfe, p_tested)

  tab1 <- tab1 %>%
    # remove = Yes
    mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
    # to get labs and units in place
    mutate(
      var_tmp = str_split(var, " = ", simplify = TRUE)[, 1],
      val_tmp = str_split(var, " = ", simplify = TRUE)[, 2],
      # if recoding or categorizing will still get org label
      var_tmp2 = str_replace_all(var_tmp, "(_cat2|_cat)", ""),
      # if shf/sos combination  will still get org label
      var_tmp2 = str_replace_all(var_tmp2, "shf_sos_com_", "sos_com_"),
    )

  tab1 <- left_join(tab1,
    meta.variables.Sheet.1 %>%
      select(variable, label, unit),
    by = c("var_tmp2" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, var_tmp),
      Variable = if_else(!is.na(unit),
        paste0(Variable, " (", unit, ")"),
        Variable
      ),
      Variable = if_else(val_tmp != "",
        paste0(Variable, " ", val_tmp),
        Variable
      )
    )

  # footnotes
  tab1 <- tab1 %>%
    mutate(
      footnote1 = if_else(str_detect(var, "^shf_"), footnote_marker_symbol(1), ""),
      footnote2 = if_else(str_detect(var, "sos_"), footnote_marker_symbol(2), ""),
      footnote3 = if_else(str_detect(var, "^scb_"), footnote_marker_symbol(3), ""),
      footnote4 = if_else(var_tmp %in% modvars, footnote_marker_symbol(4), ""),
      footnote5 = if_else(str_detect(var, "^scb_dispincome_cat"), footnote_marker_symbol(5), "")
    ) %>%
    unite(footnote, starts_with("footnote"), sep = "")

  tab1xls <- tab1 %>%
    mutate(footnotexls = if_else(var_tmp %in% modvars, "*", "")) %>%
    mutate(Variable = paste0(Variable, footnotexls)) %>%
    select(Variable, Missing:p_tested)

  ## fix in order to use escape = TRUE
  colnames(tab1xls) <- c(
    "Variables", "Missing (%)", "Tested", "Not tested", "p-value", "Tested", "Not tested", "p-value", "p-value tested (WHFE vs NWFE)"
  )

  write.xlsx(tab1xls, paste0(
    "./output/tabs/Baseline characteristics ",
    tabname, "_", Sys.Date(), ".xlsx"
  ),
  rowNames = FALSE, overwrite = TRUE
  )

  tab1 <- tab1 %>%
    mutate( # so no probs
      Variable = sanitize_text(Variable),
      Variable = paste0(Variable, footnote),
      # space in Latex output (fix this other way?)
      Variable = sub("  ", ". ", Variable)
    ) %>%
    select(Variable, Missing:p_tested)

  ## fix in order to use escape = TRUE
  colnames(tab1) <- sanitize_text(c(
    "Variables", "Missing (%)", "Tested", "Not tested", "p-value", "Tested", "Not tested", "p-value", "p-value tested"
  ))

  footnote(
    default_kable(tab1,
      font_size = 6,
      caption = paste0("Baseline characteristics ", tabname),
      longtable = TRUE,
      escape = FALSE
    ) %>%
      add_header_above(c(" " = 1, " " = 1, "WHFE" = 3, "NWHFE" = 3, "WHFE vs NWFE" = 1)) %>%
      landscape(),
    general = c(
      "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
    ),
    symbol = c(
      "Source: SwedeHF",
      "Source: KON/VAL",
      "Source: SCB",
      "Included in the multiple imputation model (althought not necessarily imputed if there is no missing data) and logistic/cox models.",
      "Medium within index year"
    )
  )
}
```

```{r tab1, cache=cacheon, dependson="tab1func"}
tab1func(rsdata, "")
```

```{r tab1ref, cache=cacheon, dependson="tab1func"}
tab1func(rsdata %>% filter(shf_ef_cat == "HFrEF"), " - HFrEF")
```
